### 🔐 Login de Usuário
POST http://localhost:3000//apiuser/login
Content-Type: application/json

{
  "email": "usuario@email.com",
  "password": "suaSenhaAqui"
}

###

### 📝 Registro de Usuário
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "name": "João",
  "email": "joao@example.com",
  "password": "123456"
}

###

### 📚 Buscar todos os cursos
GET http://localhost:3333/curso/findall

###

### 🔎 Buscar curso por nome
GET http://localhost:3333/curso/findnome?nome=Engenharia

